In [16]:
# Import the required libraries
import numpy as np
import pandas as pd
import hvplot.pandas
from pathlib import Path
from pandas.tseries.offsets import DateOffset
from finta import TA

In [17]:
# Read in our cleaned data
df = pd.read_csv("../resources/cleaned_data.csv")
df.head()

,Date,/ES,AAPL Last,AAPL Bid,AAPL BS,AAPL Ask,AAPL AS,AAPL Volume,AAPL Open,AAPL High,...,QQQ BS,QQQ Ask,QQQ AS,QQQ Volume,SPY Last,SPY Bid,SPY BS,SPY Ask,SPY AS,SPY Volume
0,2024-01-16 03:59:59,4792.25,185.92,183.62,1.0,183.77,8.0,2818.0,0.0,0.0,...,10,406.62,8,927.0,476.68,474.22,25,474.37,6,453.0
1,2024-01-16 04:00:02,4792.00,185.92,183.62,1.0,183.77,9.0,2960.0,0.0,0.0,...,10,406.63,8,1461.0,476.68,474.23,25,474.35,1,466.0
2,2024-01-16 04:00:05,4792.25,185.92,183.62,1.0,183.77,9.0,3023.0,0.0,0.0,...,10,406.65,8,1489.0,476.68,474.23,25,474.36,14,492.0
3,2024-01-16 04:00:08,4792.25,185.92,183.62,1.0,183.77,8.0,3075.0,0.0,0.0,...,9,406.65,8,1557.0,476.68,474.23,25,474.36,5,503.0
4,2024-01-16 04:00:11,4792.50,185.92,183.62,1.0,183.76,1.0,3109.0,0.0,0.0,...,9,406.69,8,1611.0,476.68,474.27,25,474.39,5,523.0

In [19]:
df.rename(columns={"AAPL Last": "close", "AAPL Open": "open", "AAPL High": "high", "AAPL Low": "low"}, inplace=True)

In [23]:
only_aapl_df = df['close', 'open', 'low', 'high']

KeyError: ('close', 'open', 'low', 'high')

In [18]:
# Create indicators
df[("AAPL pct change")] = df[("AAPL Last")].pct_change()

# Simple Moving Averages
df["AAPL_SMA5"] = TA.SMA(df["AAPL Last"],5)
df["AAPL_SMA10"] = TA.SMA(df["AAPL Last"],10)
df["AAPL_SMA20"] = TA.SMA(df["AAPL Last"],20)
df["AAPL_SMA50"] = TA.SMA(df["AAPL Last"],50)
df["AAPL_SMA200"] = TA.SMA(df["AAPL Last"],200)

# Exponential Moving Averages
df["AAPL_EMA3"] = TA.EMA(df["AAPL Last"],3)
df["AAPL_EMA9"] = TA.EMA(df["AAPL Last"],9)
df["AAPL_EMA20"] = TA.EMA(df["AAPL Last"],20)
df["AAPL_EMA50"] = TA.EMA(df["AAPL Last"],50)
df["AAPL_EMA100"] = TA.EMA(df["AAPL Last"],100)

AttributeError: 'int' object has no attribute 'rename'